version: '3'
services:
  mysql:
    image: mysql:8.0
   
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./data:/var/lib/mysql

     
# Names our volume
volumes:
      data:
